---
layout: cv
title: Nathan Hinkson's CV
---
---
title: "Nathan Hinkson's Resume"
author: "Nathan Hinkson"
date: "September 26, 2024"
output: pdf_document
---

# NATHAN HINKSON  
540-422-6455 | nathan.hinkson@gmail.com | [LinkedIn Profile](https://www.linkedin.com/in/nathan-hinkson/)

---

## EDUCATION  
**Bachelor of Science in Business Analytics**  
**Brigham Young University - Idaho** — Rexburg, Idaho  
Minor: Automotive Technology  
September 2021 – July 2025  
- Area of Interest: Finance and Consulting  
- Cumulative GPA: 3.55  
- Scholarship: Brigham Young University - Idaho Academic Grant  
- Relevant Coursework: Advanced Data Analytics, Predictive Modeling, Data Visualization, Financial Analytics, Business Strategy, SQL, Python, R, PowerBI, Tableau

---

## PROFESSIONAL EXPERIENCE  

**Business Analytics Intern**  
**Be Ready Enterprises LLC** — Fredericksburg, Virginia  
April 2024 – July 2024  
- Enhanced daily operations by managing customer service interactions and streamlining sales processes.  
- Developed and launched an e-commerce store, including product uploads, website design, and pre-launch preparation.  
- Leveraged third-party services to increase product visibility and boost online sales.  
- Conducted comprehensive industry analysis, evaluating competition, costs, revenues, and margins to devise actionable strategic plans for the company’s future.

**Student Consultant**  
**Small Business Management - "Barter Idaho"** — Rexburg, Idaho  
June 2023 – July 2023  
- Consulted with a team of three other individuals to research and create a business plan for an Idaho Bartering organization.  
- Devised liability waiver and transaction record templates to ensure the organization could run legally in Idaho.  
- Clarified community needs by utilizing surveys to discover how "Barter Idaho" could fulfill needs by hosting bi-weekly bartering events.

**Welder/Fitter**  
**Cives Steel Corp** — Ucon, Idaho  
November 2022 – April 2023  
- Mobilized as a team to match and exceed weekly shop goals for production.  
- Safely operated cranes around 5-10 team members in a warehouse environment to move steel beams weighing several thousand pounds.  
- Measured, built, and welded structural steel beams to be within 1/8" tolerance and meet customer and AWS standards.

**Teacher’s Assistant**  
**Automotive Lab: Electrical Systems/Engine Performance** — Rexburg, Idaho  
April 2022 – June 2022  
- Led students in diagnosing and repairing actual customer vehicles within 2-3 lab periods.  
- Trained students in applying theoretical knowledge of engine performance and electrical problems, ensuring enough practical experience in one semester for future success.

---

## VOLUNTEER EXPERIENCE  

**Full-Time Volunteer LDS Church**  
**England London Mission** — London, England  
May 2019 – May 2021  
- Served a 24-month service mission to educate people about the Church and serve the people of England.  
- Managed a full-time schedule routinely working 10-12 hours per day for 24 months.  
- Increased missionary effectiveness by providing training in individual communication, problem-solving, and working strategy skills.  
- Adapted work to meet legal requirements during the COVID-19 pandemic.  
- Led through quantitative goal setting, reviewing past goals, learning new teaching/outreach methods, and increasing team member morale.  
- Coordinated activities with religious and civic groups to provide community service and enhance exposure to local church services.



<!-- ### Footer

Last updated: September 2024 -->